### ISSUE TITLE
[Bug]: 3dsx from bundler app crashes on boot

### ISSUE THREAD

**Issue by Royerson** [lovebrew/bundler-frontend#17]
### Software Version

3.0.1

### What Happened?

The 3dsx files generated by the bundler app at https://bundle.lovebrew.org/ always crash on boot with the following error.
```
Error

[love "boot.lua"]:405: attempt to index field 'arg' (a nil value)


Traceback

[love "callbacks.lua"]:343: in function 'handler'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```
I tried making a simple project to try to track down the issue, but I couldn't get it to run even with the main.lua in the "Code to Reproduce" section of this report.

### What was Expected?

My game should run.

### Code to Reproduce

```Lua
function love.load(arg)
	x = 5
end

function love.update(dt)
	x = x + 1
end

function love.draw(screen)
    love.graphics.print('Hello World!', 0,0)
end
```

### Console

Nintendo 3DS

### Firmware Version(s)

11.17.0-50U

### Custom Firmware Version

13.1.1

### Execution Method

Homebrew Menu

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
Hm. I fixed this before I had updated the bundler. Perhaps I didn't upload the new binaries, though.

I'll get that done sometime today. In the meantime, does the game folder method work? You can set `packaged` to `false` and it will only convert assets and give you the resulting game.

**Comment by Royerson** [comment]
Yeah, converting at least png to t3x seems to work fine.

**Comment by TurtleP** [comment]
Alright I just updated the binaries. I think what happened was they were overridden by the old ones when updating the bundler. Try again now and *hopefully* it's fine. I double checked the dates on the files for the commit that fixes this and they are accurate on my pi now.

**Comment by Royerson** [comment]
It didn't work. I'm getting the exact same error.

**Comment by TurtleP** [comment]
This is weird.. the bundler isn't even adding in the zip data when it should be. I tested this before we pushed the new changes. This isn't a LÖVE Potion issue, so I'm moving it to the bundler frontend repo which is where it is applicable now.

In the meantime, if you *need* to bundle your game, do the following:

1. Upload your bundle to the website as usual
2. Check that it was bundled successfully by **opening the binary in 7-Zip**.
    - Technically anything that opens zip files *will* work, but as an example.
3. Should this not have *anything* found (see screenshot) you can [fuse games manually](https://love2d.org/wiki/Game_Distribution)
    - **Windows**: `copy /b SuperGame.3dsx+SuperGame.love SuperFused.3dsx`
    - **macOS/Linux**: `cat SuperGame.3dsx SuperGame.love > SuperFused.3dsx`
4. Now this fused game will work as it should. I've tested this with @Nawias before and just now.

These instructions should probably be mirrored on the lovebrew wiki page, I think, just in case.

I apologize for the inconvenience. Hopefully we can get this resolved sooner rather than later. I'm not an expert with JavaScript/TypeScript (and neither is Nawias) so any help debugging this front end issue would be very appreciated.

![image](https://github.com/lovebrew/lovepotion/assets/6239208/afd9b869-85a0-4561-8092-1b4f1ed0bb77)

**Comment by Royerson** [comment]
Thank you, I was able to get it working with the workaround. Good luck fixing the bundler.

**Comment by TurtleP** [comment]
Alright, bug squashed. Turns out that trying to remove the log .. for whatever logical reason I made .. for packaging on 3ds was the issue. Took a bit to fix it when pushing to production, but it's dealt with now, thankfully. Hopefully this resolves the issues other people had with the bundler with missing files.
